### ISSUE TITLE
Docker Build Issues

### ISSUE THREAD

**Issue by tiredofit** [logchimp/theme#15]
**Describe the bug**
Unable to build non interactively with Docker

**To Reproduce**
Steps to reproduce the behaviour:
1. (using tiredofit/nginx:latest) `apk add git nodejs yarn`
2. `yarn build --fix` within Dockerfile

**Expected behaviour**
Builds properly. It builds with the actual base Docker image in a bash shell, just not in Docker.

**Examples of Errors**
````
/app/theme/src/pages/Index.vue
  4:9  error  Replace `⏎↹↹↹↹v-for="post·in·posts"⏎↹↹↹↹:key="post.postId"⏎↹↹↹↹:post="post"⏎↹↹↹` with `·v-for="post·in·posts"·:key="post.postId"·:post="post"·`  prettier/prettier

/app/theme/src/pages/Join.vue
   9:5   error  Insert `/`                                                                                                                                          prettier/prettier
  41:12  error  Replace `⏎↹↹↹↹↹type="primary"⏎↹↹↹↹↹:loading="buttonLoading"⏎↹↹↹↹↹@click="join"⏎↹↹↹↹` with `·type="primary"·:loading="buttonLoading"·@click="join"`  prettier/prettier
````

and more..

**Additional thoughts**
Looks to be problems with tabs. Standardize to spacing instead of tabs to avoid this issue. The `--fix` argument shouldn't need to be used regardless.

**Comment by mittalyashu** [comment]
That's a known issue, for a work-around you can disable prettier Error in `.eslintrc.js`

**Comment by tiredofit** [comment]
Still doesn't resolve it, Vue compilation throws errors now due to mixture of spaces and tabs.

````

Module Error (from ./node_modules/eslint-loader/index.js):

/app/theme/src/pages/boards/_url.vue
  147:5  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs

````

Will wait for another commit.

**Comment by ItsMrReals** [comment]
Can confirm ^

**Comment by mittalyashu** [comment]
Thank you the confirmation, will look into the issue.
